"""Type protocols for Redis clients consumed by the store implementations."""

from __future__ import annotations

from collections.abc import Awaitable
from typing import Any, Protocol


class SyncRedisPipeline(Protocol):
    def delete(self, *names: str) -> SyncRedisPipeline: ...

    def execute(self) -> list[Any]: ...

    def __enter__(self) -> SyncRedisPipeline: ...

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...


class SyncRedisClient(Protocol):
    def smembers(self, name: str) -> set[Any]: ...

    def sadd(self, name: str, *values: str) -> int: ...

    def srem(self, name: str, *values: str) -> int: ...

    def lrange(self, name: str, start: int, end: int) -> list[Any]: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...

    def pipeline(self, transaction: bool = True) -> SyncRedisPipeline: ...

    def zrevrange(self, name: str, start: int, end: int) -> list[Any]: ...

    def zscan(
        self,
        name: str,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> tuple[int, list[tuple[Any, float]]]: ...


class AsyncRedisPipeline(Protocol):
    def delete(self, *names: str) -> AsyncRedisPipeline: ...

    def execute(self) -> Awaitable[list[Any]]: ...


class AsyncRedisClient(Protocol):
    def smembers(self, name: str) -> Awaitable[set[Any]]: ...

    def sadd(self, name: str, *values: str) -> Awaitable[int]: ...

    def srem(self, name: str, *values: str) -> Awaitable[int]: ...

    def lrange(self, name: str, start: int, end: int) -> Awaitable[list[Any]]: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Awaitable[Any]: ...

    def pipeline(self, transaction: bool = True) -> AsyncRedisPipeline: ...

    def zrevrange(self, name: str, start: int, end: int) -> Awaitable[list[Any]]: ...

    def zscan(
        self,
        name: str,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> Awaitable[tuple[int, list[tuple[Any, float]]]]: ...
